### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by okseb** [flathub/io.github.Foldex.AdwSteamGtk#41]
When I try to run it I get this error.

`Traceback (most recent call last):
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/main.py", line 122, in do_activate
    win = AdwaitaSteamGtkWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/window.py", line 76, in __init__
    self.load_app_style()
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/window.py", line 99, in load_app_style
    ret, msg = style.generate_style(selected_theme)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/style.py", line 76, in generate_style
    css += format_css("accent_color", css_vars["accent"])
                                      ~~~~~~~~^^^^^^^^^^
KeyError: 'accent'`

**Comment by Foldex** [comment]
Fixed in https://github.com/Foldex/AdwSteamGtk/commit/758d290eb687a2bfdbf9e99036f1b7938e3382fb
